unauthorized_text: str = "Вы не авторизованы. Обратитесь к владельцу бота."
greetings_text: str = "Привет {}."
input_text: str = "\nНапиши в чат текст заметки."
fault_text: str = "Принимаются только текстовые сообщения."
success_text: str = "Заметка отправлена."
error_text: str = "Ошибка отправки. Что-то пошло не так."
